### PR TITLE
Feature/improvements

### PR DESCRIPTION
**Pull request by JeroenBer**
- Fixed running on docker linux
- Added ignore null handling since for json serialization (necessary for some apple payloads)

### CODE REVIEW

**Comment by shivammalhotra** [comment]
@JeroenBer  @andrei-m-code Thank you 

**Here is my experience**:
I was trying to use corepush nuget to send notification to apple devices. 
From an AWS lambda framework 2.1. 
First I got exception "Windows Cryptography Next Generation (CNG) is not supported on this platform."
After that I used @andrei-m-code changes.
Then on 2.1 framework it still failed with exception "the server returned an invalid or unrecognized response."
So I updated to Net Core 3.1 and finally was able to send notification. So thanks for your efforts.

**Comment by andrei-m-code** [comment]
@shivammalhotra thank you for your feedback. Can you confirm that @JeroenBer 's changes are necessary?

**Comment by shivammalhotra** [comment]
@andrei-m-code Yes I did verify that. 

After everything was working. I went back to using the nuget and again got the exception
 "Windows Cryptography Next Generation (CNG) is not supported on this platform.". 

So yes @JeroenBer 's changes are required.

**Comment by andrei-m-code** [comment]
@shivammalhotra great to hear that. Thanks for using the library, I've released a new package 2.1.1 with these changes included. Hope it works for you.

@JeroenBer thank you for your contribution. Really appreciate it.

**Comment by JeroenBer** [comment]
Great you merged it, I think your library is superb, I just needed this basic functionality for my project. In the near future I will also make a PR for simple Windows Push Notification Services (WNS) support.

**Comment by andrei-m-code** [comment]
@JeroenBer the library is very simple :), thank you again!

**Pull request merged**
